language: node_js
node_js: node
dist: trusty
before_install:
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo add-apt-repository -y ppa:wine/wine-builds
- sudo apt-get update
- sudo apt-get install -y wine-staging devscripts build-essential lintian dh-make
  rpm yarn
- echo "deb http://ftp.debian.org/debian jessie-backports main" | sudo tee /etc/apt/sources.list.d/jessie-backports.list
- sudo apt-get update
- sudo apt-get -t jessie-backports install -y --force-yes flatpak flatpak-builder
install:
- yarn
before_script:
- export WINEDLLOVERRIDES="mscoree,mshtml="
- export PATH=$PATH:/opt/wine-staging/bin/
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- rm -rf rpmbuild/
- mkdir -p rpmbuild/SOURCES
- tar -cjf rpmbuild/SOURCES/dummy.tar.bz2 readme.md
script:
- yarn run build:linux
- debuild --no-lintian -b -uc -us
- yarn run build:osx
- yarn run build:win
- yarn run build:linuxarmv7l
- debuild --no-lintian -b -uc -us -aarmhf
- cd rpmbuild && rpmbuild --define "_topdir $(pwd)/" -bb ../whatsupp.spec
  && cd ..
- yarn run build:linux32
- yarn run build:appimage
- yarn run build:flatpak64
before_deploy:
- sudo apt-get install -y zip tar gzip
- cd dist/ && zip -qr WhatsUpp-${TRAVIS_TAG}-win32-x64.zip WhatsUpp-win32-x64/ && cd
  ..
- cd dist/ && zip -yqr WhatsUpp-${TRAVIS_TAG}-darwin-x64.zip WhatsUpp-darwin-x64/ &&
  cd ..
- cd dist/ && tar czf WhatsUpp-${TRAVIS_TAG}-linux-ia32.tar.gz WhatsUpp-linux-ia32/
  && cd ..
- cd dist/ && tar czf WhatsUpp-${TRAVIS_TAG}-linux-x64.tar.gz WhatsUpp-linux-x64/
  && cd ..
- cd dist/ && tar czf WhatsUpp-${TRAVIS_TAG}-linux-armv7l.tar.gz WhatsUpp-linux-armv7l/
  && cd ..
- export RELEASE_AMD64_PKG_FILE=$(ls ../whatsupp*amd64.deb)
- export RELEASE_ARM_PKG_FILE=$(ls ../whatsupp*armhf.deb)
- export RELEASE_AMD64_RPM_FILE=$(ls rpmbuild/RPMS/x86_64/*.rpm)
- export RELEASE_APPIMAGE_FILE=$(ls dist/whatsupp*-x86_64.AppImage)
deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
    file_glob: true
    file:
    - dist/WhatsUpp-${TRAVIS_TAG}-win32-x64.zip
    - dist/WhatsUpp-${TRAVIS_TAG}-darwin-x64.zip
    - dist/WhatsUpp-${TRAVIS_TAG}-linux-x64.tar.gz
    - dist/WhatsUpp-${TRAVIS_TAG}-linux-ia32.tar.gz
    - dist/WhatsUpp-${TRAVIS_TAG}-linux-armv7l.tar.gz
    - "${RELEASE_AMD64_PKG_FILE}"
    - "${RELEASE_ARM_PKG_FILE}"
    - "${RELEASE_AMD64_RPM_FILE}"
    - "${RELEASE_APPIMAGE_FILE}"
    - dist/eu.alindt.whatsupp_master_x64.flatpak
    api_key:
      secure: TX/psfzZ+R8Ua7y/uWUSFLVzajfANM/flNyDO5bG9X/LqURoWOQEnjmvUYV4xBp9IJM/xc5/icvUfl2DyNPunmZdRtVv0M85JhkKkQ0wywGhSHENo33kAWDn9v9gFb5w/cRpkghHOYUH9C7GLSulVxtuyb4FacrvvUdqr6kcth9gzWAqG3MBJNID+sI0/JooyGdu2VTMaszlImyzM4m76UQVl9K09ZCQbtoSlnVGYBhkMbu13gh750LWFbdf02KUkEO3TxQ8WYRMJ1VaXy0j/qcCi3mFAQxWxwvvxDrayNuZPoqLcfp0FFJLtqwT+QIaCPHpWwUWiiAHpLWNj/OmzEk7NkmTkKJ44ToBnJgAs3KibEvS+qrXdUO9qOWYUFG27EkCjQSppSWtZmn9EkY4BilSp6lFL8fPQWcjzvT7tkoQUs//g+cgyYHu5t3fgT3Ld1FuSkbpCzixxwbfWzUnR+jco0aWmtAT6f1wpbHmWAWEUI12SNEy8BtnvyZdXCGIYJFD7vJEM9i8NoT/ztvW1uXq7zqN8IZAFYt6BwmgHSWJ/KKsvaD9itOApVJCWEZy/JH7bm/7iE1z9KjWfUelfIwLAc1VJ5HHtEVfeLdz1oCwQ/WXSPeasQuMPqxrBFgHteyz6zdg1cgY3BoiLMZFpyaafYKdLYpDS9pS7rTuvuM=
  - provider: packagecloud
    repository: WhatsUpp
    username: alindt
    skip_cleanup: true
    on:
      tags: true
    package_glob: ../*.deb
    dist: "debian/stretch"
    token:
      secure: NV4SYlKo3/jPzhqD4TMO6aU0TjmfmLpQWFXvUzHD84BS92a9LpqZTA7P/aKH1abHQgkomJA4saQo9y0QUP3CoJMsS0srePpv2KwO1SbMzHsozJ26zICnZnC2JZQBZbmgzAzHxKpiXqTVxg7Lm3ixWGdVOzQGePYJSxm7yQWitz2YyKnxzRf36gp05bb3ADNm8sp03rcLHd5Wz7aAwJ+phUlHIwCwGJllSBYhM2LnCcx7OYVRVYuOHz4/K+Dlm5v2Q8e8jn9cJuca1SROTSPkzacz9WjEwZxpo/cJIPstHbIBhkX+NA2zDMCcmQ5X10pcyNlTJMhhkrsVRb1z4GveX04U5mdKDOfNEvoDdkFUhSMmg8U9n4r+4DE3d9LRpbN6mCpbDeuZ2Owswkgfd+ZMS2a2bxMs5eW3fwt9XCKiRJX3x15twnWLZZ7CFM0bdUaZ/K1A4JTkVBm3jpaOgytQQ6TBVKzyQoRijUpvSGBi5tKDZlG5tJgYAuZM8dzdaWcL8zsECsPkUJaFyOHftWAtXe7IGP3aip3APugvKZLTptvPq+lEjZPl4XuaHbuwRnliAV/Fn6riyftuBWFEKyPyEAtS3MLcrQuxauKNu9rW2dy6JF58mYgtm6jUzuRYFR9dwNaAzOKCPNfEAyx7dTa4eaUXO9bxDUWpPs5sBD8R2u4=
  - provider: packagecloud
    repository: WhatsUpp
    username: alindt
    skip_cleanup: true
    on:
      tags: true
    package_glob: "${RELEASE_AMD64_RPM_FILE}"
    dist: "fedora/27"
    token:
      secure: NV4SYlKo3/jPzhqD4TMO6aU0TjmfmLpQWFXvUzHD84BS92a9LpqZTA7P/aKH1abHQgkomJA4saQo9y0QUP3CoJMsS0srePpv2KwO1SbMzHsozJ26zICnZnC2JZQBZbmgzAzHxKpiXqTVxg7Lm3ixWGdVOzQGePYJSxm7yQWitz2YyKnxzRf36gp05bb3ADNm8sp03rcLHd5Wz7aAwJ+phUlHIwCwGJllSBYhM2LnCcx7OYVRVYuOHz4/K+Dlm5v2Q8e8jn9cJuca1SROTSPkzacz9WjEwZxpo/cJIPstHbIBhkX+NA2zDMCcmQ5X10pcyNlTJMhhkrsVRb1z4GveX04U5mdKDOfNEvoDdkFUhSMmg8U9n4r+4DE3d9LRpbN6mCpbDeuZ2Owswkgfd+ZMS2a2bxMs5eW3fwt9XCKiRJX3x15twnWLZZ7CFM0bdUaZ/K1A4JTkVBm3jpaOgytQQ6TBVKzyQoRijUpvSGBi5tKDZlG5tJgYAuZM8dzdaWcL8zsECsPkUJaFyOHftWAtXe7IGP3aip3APugvKZLTptvPq+lEjZPl4XuaHbuwRnliAV/Fn6riyftuBWFEKyPyEAtS3MLcrQuxauKNu9rW2dy6JF58mYgtm6jUzuRYFR9dwNaAzOKCPNfEAyx7dTa4eaUXO9bxDUWpPs5sBD8R2u4=
