# vim: set ts=2 sw=2 expandtab:

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update
            sudo apt-get install --no-install-recommends yarn fakeroot

      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}-{{ checksum "app/yarn.lock" }}-{{ checksum "package.json" }}-{{ checksum "app/package.json" }}
            - yarn-packages-v1-{{ checksum "yarn.lock" }}-{{ checksum "app/yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - yarn-packages-v1

      - run:
          name: Yarn Install
          command: |
            /usr/bin/yarn install

      - save_cache:
          paths:
            - node_modules
            - app/node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}-{{ checksum "app/yarn.lock" }}-{{ checksum "package.json" }}-{{ checksum "app/package.json" }}

      - run: /usr/bin/yarn build:linux64
      - run: /usr/bin/yarn build:linux32
      - run: /usr/bin/yarn pkg:debian64
      - run: /usr/bin/yarn pkg:debian32
